### ISSUE TITLE
Data in game doesn't show correctly compared to the ones modified in config

### ISSUE THREAD

**Issue by betterworld-sjq** [ZsoltMolnarrr/ProjectileDamage#10]
I changed the damages from 6 9 to 4 8 in config，but in game they still show 6 9.
Ver 1.20.1 forge

**Comment by betterworld-sjq** [comment]
I changed the damages from 6 9 to 4 8 in config，but in game they still show 6 9.
Ver 1.20.1 forge

**Comment by ZsoltMolnarrr** [comment]
The values in question don't modify the damage of vanilla Bow and Crossbow items.
These values are used when automatically assigning projectile damage to 3rd party (mod content) bows.
