### ISSUE TITLE
[1.20.1] How can modpack creators utilize this?

### ISSUE THREAD

**Issue by Cixon** [ZsoltMolnarrr/ProjectileDamage#11]
I made a suggest a while ago about adding datapack integration but I’m not sure if anything was done with that or if it’s still planned.

I’d like to customize both vanilla and modded projectile weaponry damage output with this mod - please let me if there’s anything I can do, thanks!

**Comment by Veynam** [comment]
Yeah no clue either, doesnt seem to work with custom bows. I could be doing something wrong.

**Comment by ZsoltMolnarrr** [comment]
This mod provides a Java API only.
