### ISSUE TITLE
Improper Projectile Damage Attribute Application

### ISSUE THREAD

**Issue by Atsumachi** [ZsoltMolnarrr/ProjectileDamage#15]
Minecraft: **1.20.1**
Fabric Loader: **0.15.11**
Fabric API: **0.92.1+1.20.1**

Archers (RPG Series): **v1.2.1+1.20.1**
Ranged Weapon API: **v1.1.1+1.20.1**

Zenith: **1.1.9-1.20.1**
Zenith Attributes: **0.2.4**
Zephyr: **v0.4.1+1.20.1**

**Issue:**
- I came across a bug when using Zenith + Zephyr in regards to Projectile Damage attribute application to weapons. When the Projectile Damage attribute is applied to bows and crossbows, it causes the damage of bows added from Archers (RPG Series) to get significantly reduced. I'm using Zenith + Zephyr because I couldn't figure out how to apply that attribute using in game commands.
![image](https://github.com/muon-rw/Zephyr/assets/89116003/faf9d153-076d-4ca5-badc-e0094545eacf)
![output2 webm_snapshot_00 35_ 2024 05 20_23 01 32](https://github.com/muon-rw/Zephyr/assets/89116003/6557e008-6b84-4c46-89ed-469f07b24832)
![image](https://github.com/muon-rw/Zephyr/assets/89116003/99f2ac1c-bc31-4aa4-921f-7f4c952fa049)
![output2 webm_snapshot_00 32_ 2024 05 20_23 01 13](https://github.com/muon-rw/Zephyr/assets/89116003/38e411a7-6d52-4685-80cd-423167460396)

**Reproduction:**
- Reforge any bow or crossbow that's added by Archers (RPG Series) and roll for a "Projectile Damage" attribute.

**Note:**
-  I reported this to muon from Zephyr and am reporting it here as well just in case.

**Comment by ZsoltMolnarrr** [comment]
Too many interfering mods.
Remove Projectile Damage mod, since it is deprecated.
Remove whatever is adding Arrow Velocity.
