### ISSUE TITLE
DragonLoot Support Request

### ISSUE THREAD

**Issue by NolanHewitt** [ZsoltMolnarrr/ProjectileDamage#18]
The mod dragonloot (https://www.curseforge.com/minecraft/mc-mods/dragonloot) seems to be willing to implement ProjectileDamage/Ranged Weapon API but wants someone to make a PR for it. I'm not that knowledgeable on making modding stuff so was wondering if someone from this project could add support to it? Would be nice to see this added to a pretty popular mod.

**Comment by ZsoltMolnarrr** [comment]
It is the other way around my friend.
Mods need to rely on APIs, not APIs on content mods. This is an engineering practice.

Morover, this library is now deprecated.
Fabric projects need to use the Ranged Weapon API mod.
For Forge I no longer develop such feature.

**Comment by NolanHewitt** [comment]
Understandable. Seems someone actually did make a PR to add this to dragonloot at some point but not ranged weapon api.
