### ISSUE TITLE
Jar in Jar, or set as dependency?

### ISSUE THREAD

**Issue by Andrew6rant** [ZsoltMolnarrr/ProjectileDamage#2]
Hello, I'm a mod developer who is planning on using this library in my mod, [Tiered](https://github.com/Andrew6rant/tiered). Here is a small showcase of the integration:

![image](https://user-images.githubusercontent.com/57331134/178627035-d525ef80-f56a-4e4e-becb-c1454e94618b.png)

![image](https://user-images.githubusercontent.com/57331134/178626776-cf0947b3-d4cb-4abb-92a1-a1f99aec6f85.png)

Would you prefer I embed this library in the mod, or should I set it as a dependency?

Thanks!

**Comment by ZsoltMolnarrr** [comment]
Hello!
I am glad you find this mod useful:)
Please support the development by not embedding, so my mod gets download revenue too.

**Comment by Andrew6rant** [comment]
Alright, I will make sure to mark the dependency when I release the mod. Thank you!

Also, I recommend mixing into PersistentProjectileEntity so that your attribute actually does the proper damage. Vanilla Minecraft rounds the values.

My mod, [Precise Damage](https://github.com/Andrew6rant/precise-damage), does this. If you want, you can depend on or embed the mod, or just nab the mixin itself.
