### ISSUE TITLE
Power enchantment compat

### ISSUE THREAD

**Issue by ConqAra** [ZsoltMolnarrr/ProjectileDamage#5]
Can you make it so power enchantment displays the additional projectile damage like sharpness does for swords/axes? Would be really nice qol!

**Comment by ZsoltMolnarrr** [comment]
Does sharpness do that?
Can you provide an example screenshot or something please?

**Comment by ConqAra** [comment]
![image](https://user-images.githubusercontent.com/76233356/213543344-fa99a720-f084-411f-82df-6b9d68fb7ea2.png)

Yeah it shows the extra damage in the dmg tool tip, instead of 7 it shows 10 when you have sharpness

**Comment by ConqAra** [comment]
Although it was modded, so ill try it really quick with vanilla client to make sure

**Comment by ConqAra** [comment]
![image](https://user-images.githubusercontent.com/76233356/213544501-aad5f5b3-544d-421f-b772-e7b0a980c51b.png)
Yup, does it in vanilla too!

**Comment by ZsoltMolnarrr** [comment]
After additional consideration, I think this would be incorrect to implement.
Considering that armor can also grant projectile damage, there is no way to accurately display the projectile damage combined from every sources with power enchantment.

**Comment by ConqAra** [comment]
I mean, damage is also not correctly displayed regardless because smite (would only provide the additional dmg for certain mobs) and other modded enchantments, that do extra damage that it wont account for, will not display the change. minecraft doesn't properly display damage either in that case, its more of a "this item with this enchantment specifically does this much dmg" and then its up to the player to do the math afterwards with all those other enchantments/effects that alter attributes.

detecting and displaying the result of math for every source of damage is unreasonable. it was more of a simple quality of life to see your damage for power just like sharpness. it doesn't have to be 100% correct its just nice to have.

**Comment by ConqAra** [comment]
I'm not here to argue though, it's completely up to you to implement or not. I was just giving my insight on it.

**Comment by ZsoltMolnarrr** [comment]
I was thinking long about this, and there is no way this could work anything other than Vanilla Bow. :(
Power Enchantment is considered with arbitrary multiplication values, so modded bow can make any calculation based on the applied level. As long as Vanilla Minecraft doesn't change to allow any kind of support for this, I cannot implement this.

Thanks for the suggestion tho, the idea itself is great!
