### ISSUE TITLE
[bug] Projectile Damage settings/config don't work

### ISSUE THREAD

**Issue by qVoidreaver** [ZsoltMolnarrr/ProjectileDamage#6]
(Forge Version 1.18.2)

Projectile Damage settings don't work

![bug1](https://user-images.githubusercontent.com/106211252/226158221-5c537340-e7f2-4fea-9478-3f3a642fa3b2.png)

![bug2](https://user-images.githubusercontent.com/106211252/226158226-00f4921d-8fbc-4b39-bf77-5ee014bf2807.png)

And yes, it's not just visual, it really doesn't change anything.

Plss, fix this, it's unbalancing my modpack ;-;

**Comment by ZsoltMolnarrr** [comment]
This config value represents the value that is meant to be assigned to other bows and crossbows (added by mods).
I understand the config name is missleading, but there is not bug here.
The the damage of vanilla weapons is not meant to be changed.
