### ISSUE TITLE
Mod compatability?

### ISSUE THREAD

**Issue by Burning-Water** [ZsoltMolnarrr/ProjectileDamage#7]
Would we be able to add modded compatibility by pulling a bows ID and stats and adding the tooltip to those as well?

**Comment by ZsoltMolnarrr** [comment]
Mod developers need to integrate this mod to define their custom bow/crossbow damage.
How this can be done, is documented here: https://github.com/ZsoltMolnarrr/ProjectileDamage#configuring-items
For chatting I recommend using the project discord.

**Comment by Burning-Water** [comment]
ah i see thanks for that, is it possible for users to add this compatibility themselves? possibly by adding the item into a config file? or maybe an in-game item similar to a name tag?

**Comment by ZsoltMolnarrr** [comment]
Players are not yet able to perform this configuration, since this was primarily designed for developers.
There will be a feature to support this in the future.
